services:
  - type: web
    name: threat-monitor
    runtime: docker
    port: 8000  # Expose Streamlit only
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.10
    healthCheckPath: /
    autoDeploy: true 