services:
  - type: web
    name: streamlit
    runtime: docker
    port: 8501
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.10
    
  - type: web
    name: fastapi
    runtime: docker
    port: 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.10
    healthCheckPath: /
    autoDeploy: true
    port: 8000  # Must match Streamlit port 