services:
  - type: web
    name: threat-api
    runtime: python
    pythonVersion: "3.10"
    command: "uvicorn run:app --host 0.0.0.0 --port 8000"
    port: 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.10
    healthCheckPath: /health
    autoDeploy: true 