services:
  - type: web
    name: cyber-threat-monitor
    env: docker
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.10
      - key: PORT
        value: 8000
    ports:
      - port: 8000
    healthCheckPath: /
    autoDeploy: true
    runtime: docker
    port: 8000  # Nginx will handle both services 