name: cyber_threat_monitor
description: A real-time cyber threat monitoring mobile app
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^15.1.0
  fl_chart: ^0.65.0
  intl: ^0.17.0
  flutter_secure_storage: ^8.0.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 